version: '3.9'

services:
  docs:
    image: ghcr.io/context-hub/docs:latest
    restart: always
    environment:
      NUXT_PUBLIC_GTAG_ID: ${NUXT_PUBLIC_GTAG_ID}
    ports:
      - 9001:80
    networks:
      - ch-docs

networks:
  ch-docs:
    ipam:
      driver: default
      config:
        - subnet: 172.0.62.0/24
