version: '3.9'

services:
  docs:
    image: ghcr.io/context-hub/doc:latest
    restart: always
    ports:
      - 9001:80
    networks:
      - ch-docs

networks:
  ch-docs:
    ipam:
      driver: default
      config:
        - subnet: 172.0.62.0/24